# Generated by Django 3.1.12 on 2025-03-18 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('role', models.IntegerField(choices=[(1, 'User'), (2, 'Super User'), (3, 'Admin')], default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('terms_conditions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostSummarySection',
            fields=[
                ('_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Cost Section',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='CostSummary',
            fields=[
                ('_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=50)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('certified_payments', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('accrued_payments', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_expenditure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variance_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variance_period', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_summaries', to='web_app.costsummarysection')),
            ],
            options={
                'verbose_name_plural': 'Cost Summary',
            },
        ),
    ]
