# Generated by Django 3.1.12 on 2025-03-19 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSumSection',
            fields=[
                ('_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Contract Sum Section',
            },
        ),
        migrations.CreateModel(
            name='ContractSum',
            fields=[
                ('_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=50)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_sum', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('certified_payments', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_sums', to='web_app.contractsumsection')),
            ],
            options={
                'verbose_name_plural': 'Contract Sum',
            },
        ),
    ]
