# Generated by Django 3.1.12 on 2025-03-19 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_contractsum_contractsumsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeBreakDownSection',
            fields=[
                ('_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Change Break Down Section',
            },
        ),
        migrations.CreateModel(
            name='ChangeBreakDown',
            fields=[
                ('_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('ref', models.CharField(max_length=50)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('certified_payments', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_expenditure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variance_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variance_period', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_breakdown', to='web_app.changebreakdownsection')),
            ],
            options={
                'verbose_name_plural': 'Change Break Down',
            },
        ),
    ]
