# Generated by Django 3.1.12 on 2025-06-14 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_riskregister_riskregistersection'),
    ]

    operations = [
        migrations.AddField(
            model_name='changebreakdown',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='changebreakdown',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='changebreakdown',
            name='updated_by',
            field=models.CharField(default='Patrick King', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractsum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractsum',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contractsum',
            name='updated_by',
            field=models.CharField(default='Patrick King', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costsummary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costsummary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='costsummary',
            name='updated_by',
            field=models.CharField(default='Patrick King', max_length=50),
            preserve_default=False,
        ),
    ]
