# Generated by Django 3.1.12 on 2025-07-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20250614_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsum',
            name='component',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
