# Generated by Django 3.1.12 on 2025-03-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_changebreakdown_changebreakdownsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostReporting',
            fields=[
                ('_id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('interim_payments', models.CharField(max_length=50)),
                ('month', models.DateTimeField(blank=True, null=True)),
                ('forecast_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('forecast_comulative', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_comulative', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cost Reporting',
            },
        ),
    ]
